"""Generate app/src/main/java/ai/vox/companion/Vocab.kt from the shared Python vocabulary.

Source of truth: /home/khoa/VOX/finetune/vox/schema.py (+ POLICY, DEFAULTS_TEXT, the screen tie-breaker tables and
the first training wordings from generate.py). Read-only: this never writes under finetune/.

Also writes TargetVocab.kt (intent cursor mode) from finetune/data/targets-v1/policy.txt and vox/targets.py
(NONE_OPTION, POSITIONS, the role words), with its own digest.

    python3 tools/gen_vocab.py            # regenerate Vocab.kt and TargetVocab.kt
    python3 tools/gen_vocab.py --check    # exit 1 if either is stale (their finetune sources changed)
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ANDROID = HERE.parent
FINETUNE = Path(os.environ.get("VOX_FINETUNE", ANDROID.parent / "finetune"))
OUT = ANDROID / "app/src/main/java/ai/vox/companion/Vocab.kt"
OUT_TARGETS = ANDROID / "app/src/main/java/ai/vox/companion/TargetVocab.kt"
POLICY_TARGETS_FILE = FINETUNE / "data/targets-v1/policy.txt"

sys.dont_write_bytecode = True  # never drop __pycache__ into finetune/
sys.path.insert(0, str(FINETUNE))
from vox import generate as G  # noqa: E402
from vox import schema as S  # noqa: E402
from vox import targets as T  # noqa: E402


def k(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def kmap(d: dict[str, str]) -> str:
    return "linkedMapOf(\n" + "".join(f"        {k(a)} to {k(b)},\n" for a, b in d.items()) + "    )"


def klist(xs) -> str:
    return "listOf(" + ", ".join(k(x) for x in xs) + ")"


def render() -> str:
    src = b"".join((FINETUNE / "vox" / f).read_bytes() for f in ("schema.py", "generate.py"))
    digest = hashlib.sha256(src).hexdigest()[:16]
    bindings = ",\n".join(f"        {klist(seq)} to {k(a)}" for seq, a in S.DEFAULT_BINDINGS.items())
    app_only = ",\n".join(f"        {klist(seq)} to {k(a)}" for seq, a in S.APP_ONLY_BINDINGS.items())
    phrases = ",\n".join(f"        {k(a)} to {klist(ws)}" for a, ws in S.PHRASES.items())
    gwords = {g: v[0][0] for g, v in G.GESTURE_WORDS.items()}
    return f"""// GENERATED by tools/gen_vocab.py from finetune/vox/schema.py + generate.py. Do not edit by hand.
// Source digest: {digest}
package ai.vox.companion

object Vocab {{
    const val SOURCE_DIGEST = {k(digest)}

    val CONTOURS: Map<String, String> = {kmap(S.CONTOURS)}
    val DISCRETE: Map<String, String> = {kmap(S.DISCRETE)}
    val EXCURSION = {klist(S.EXCURSION)}
    val DURATION = {klist(S.DURATION)}
    val CLARITY = {klist(S.CLARITY)}
    val LOUDNESS = {klist(S.LOUDNESS)}
    val SOUNDS_LIKE = {klist(S.SOUNDS_LIKE)}

    /** Phone actions: key -> option text shown to the model (order kept). */
    val ACTIONS: Map<String, String> = {kmap(S.ACTIONS)}
    val CURSOR_ACTIONS: Map<String, String> = {kmap(S.CURSOR_ACTIONS)}

    /** Default global bindings: sound sequence -> action key. */
    val DEFAULT_BINDINGS: Map<List<String>, String> = linkedMapOf(
{bindings}
    )
    val FREED_SEQUENCES = listOf({", ".join(klist(s) for s in S.FREED_SEQUENCES)})

    /** App-only bindings: resolved by the rule table in every decider mode, never shown to a model (not in ACTIONS). */
    val APP_ONLY_ACTIONS: Map<String, String> = {kmap(S.APP_ONLY_ACTIONS)}
    val APP_ONLY_BINDINGS: Map<List<String>, String> = linkedMapOf(
{app_only}
    )

    val APPS: Map<String, String> = {kmap(S.APPS)}
    val PHRASES: Map<String, List<String>> = linkedMapOf(
{phrases}
    )

    val SCREEN_KIND = {klist(S.SCREEN_KIND)}
    val SCREEN_MEDIA = {klist(S.SCREEN_MEDIA)}
    val SCREEN_SCROLL = {klist(S.SCREEN_SCROLL)}
    val SCREEN_KEYBOARD = {klist(S.SCREEN_KEYBOARD)}

    const val POLICY = {k(G.POLICY)}
    const val DEFAULTS_TEXT = {k(G.DEFAULTS_TEXT)}

    /** Screen tie-breaker for spoken phrases (generate.py). */
    val SCREEN_NEXT: Map<String, String> = {kmap(G.SCREEN_NEXT)}
    val SCREEN_PREV: Map<String, String> = {kmap(G.SCREEN_PREV)}
    val PAUSE_WORDS = setOf({", ".join(k(w) for w in sorted(G.PAUSE_WORDS))})
    val PLAY_WORDS = setOf({", ".join(k(w) for w in sorted(G.PLAY_WORDS))})

    /** Wordings used when the app writes a profile binding as a rule sentence (first training wording each). */
    val GESTURE_WORDS: Map<String, String> = {kmap(gwords)}
    const val APP_RULE_TEMPLATE = {k(G.RULE_TEMPLATES[0][0])}
    const val GLOBAL_RULE_TEMPLATE = {k(G.GLOBAL_TEMPLATES[0][0])}
    const val DISABLE_RULE_TEMPLATE = {k(G.DISABLE_TEMPLATES[0][0])}
    const val PHRASE_RULE_TEMPLATE = {k(G.PHRASE_TEMPLATES[0][0])}

    fun screenText(kind: String, media: String, scroll: String, keyboard: String): String =
        "screen: $kind; media $media; scroll $scroll; keyboard $keyboard"
}}
"""


def render_targets() -> str:
    policy_raw = POLICY_TARGETS_FILE.read_bytes()
    policy = policy_raw.decode().rstrip("\n")
    assert policy == T.POLICY_TARGETS, "data/targets-v1/policy.txt differs from vox/targets.py POLICY_TARGETS"
    digest = hashlib.sha256(policy_raw + (FINETUNE / "vox" / "targets.py").read_bytes()).hexdigest()[:16]
    return f"""// GENERATED by tools/gen_vocab.py from finetune/data/targets-v1/policy.txt + finetune/vox/targets.py. Do not edit by hand.
// Source digest: {digest}
package ai.vox.companion

/** Intent cursor mode ("the like button" -> an on-screen element). Spec: the docstring of finetune/vox/targets.py. */
object TargetVocab {{
    const val SOURCE_DIGEST = {k(digest)}

    /** instructions of the "target" question (data/targets-v1/policy.txt, trailing newline dropped). */
    const val POLICY = {k(policy)}
    /** Always the last option. */
    const val NONE_OPTION = {k(T.NONE_OPTION)}
    /** 3x3 grid buckets, row-major: index = row * 3 + col. The middle cell is "center". */
    val POSITIONS = {klist(T.POSITIONS)}
    /** Every role the training data uses (targets.ROLE_WORDS keys). */
    val ROLES = {klist(T.ROLE_WORDS)}
}}
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    # screen_text is re-implemented in Kotlin; make sure the Python format is still the one we copied.
    assert S.screen_text("K", "M", "S", "B") == "screen: K; media M; scroll S; keyboard B", "schema.screen_text changed"
    outs = [(OUT, render()), (OUT_TARGETS, render_targets())]
    if a.check:
        stale = [f for f, text in outs if (f.read_text() if f.exists() else "") != text]
        for f in stale:
            print(f"STALE: {f} differs from its finetune sources; run python3 tools/gen_vocab.py")
        if stale:
            sys.exit(1)
        print("Vocab.kt and TargetVocab.kt are up to date")
        return
    for f, text in outs:
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text)
        print(f"wrote {f}")


if __name__ == "__main__":
    main()
