// GENERATED by tools/gen_vocab.py from finetune/data/targets-v1/policy.txt + finetune/vox/targets.py. Do not edit by hand.
// Source digest: 4aedace933e7f0cf
package ai.vox.companion

/** Intent cursor mode ("the like button" -> an on-screen element). Spec: the docstring of finetune/vox/targets.py. */
object TargetVocab {
    const val SOURCE_DIGEST = "4aedace933e7f0cf"

    /** instructions of the "target" question (data/targets-v1/policy.txt, trailing newline dropped). */
    const val POLICY = "The user is in cursor mode and said which thing on the screen they want. Each option is one element on the screen as 'label (kind, position)'. Pick the element they mean: match by meaning, not exact words, and use any position words they say. If nothing on the screen fits, pick none of these."
    /** Always the last option. */
    const val NONE_OPTION = "none of these (the thing I named is not on screen)"
    /** 3x3 grid buckets, row-major: index = row * 3 + col. The middle cell is "center". */
    val POSITIONS = listOf("top left", "top", "top right", "left", "center", "right", "bottom left", "bottom", "bottom right")
    /** Every role the training data uses (targets.ROLE_WORDS keys). */
    val ROLES = listOf("button", "tab", "text field", "list item", "image", "switch", "item")
}
