// GENERATED by tools/gen_vocab.py from finetune/vox/schema.py + generate.py. Do not edit by hand.
// Source digest: c097d50fdad96ede
package ai.vox.companion

object Vocab {
    const val SOURCE_DIGEST = "c097d50fdad96ede"

    val CONTOURS: Map<String, String> = linkedMapOf(
        "rise" to "rises from low to high",
        "fall" to "falls from high to low",
        "arch" to "rises then falls",
        "dip" to "falls then rises",
        "flat" to "stays level",
    )
    val DISCRETE: Map<String, String> = linkedMapOf(
        "pop" to "a short lip pop",
        "click" to "a tongue click",
        "hiss" to "a hiss",
    )
    val EXCURSION = listOf("small (under 2 semitones)", "medium (2-4 semitones)", "large (over 4 semitones)")
    val DURATION = listOf("very short (under 150 ms)", "short (150-400 ms)", "medium (400-1000 ms)", "long (over 1 s)")
    val CLARITY = listOf("noisy", "breathy", "clear tone")
    val LOUDNESS = listOf("quiet", "normal", "loud")
    val SOUNDS_LIKE = listOf("hum", "whistle", "talking", "laughing", "coughing", "background music", "background noise", "mouth sound")

    /** Phone actions: key -> option text shown to the model (order kept). */
    val ACTIONS: Map<String, String> = linkedMapOf(
        "swipe_up" to "swipe up",
        "swipe_down" to "swipe down",
        "swipe_left" to "swipe left",
        "swipe_right" to "swipe right",
        "tap" to "tap the screen",
        "double_tap" to "double-tap the screen",
        "long_press" to "long-press / hold",
        "back" to "go back",
        "home" to "go to the home screen",
        "recents" to "open recent apps",
        "notifications" to "open the notification shade",
        "scroll_up" to "scroll up a little",
        "scroll_down" to "scroll down a little",
        "zoom_in" to "zoom in",
        "zoom_out" to "zoom out",
        "next_item" to "next item (video, song, page)",
        "previous_item" to "previous item (video, song, page)",
        "play_pause" to "play or pause media",
        "volume_up" to "turn the volume up",
        "volume_down" to "turn the volume down",
        "open_camera" to "open the camera",
        "take_photo" to "take a photo",
        "like" to "like / favourite the current item",
        "listen_for_phrase" to "listen for a spoken phrase",
        "none" to "do nothing (not a deliberate command: noise, speech, or unclear)",
    )
    val CURSOR_ACTIONS: Map<String, String> = linkedMapOf(
        "move_up_slow" to "move cursor up slow",
        "move_up_fast" to "move cursor up fast",
        "move_down_slow" to "move cursor down slow",
        "move_down_fast" to "move cursor down fast",
        "move_left_slow" to "move cursor left slow",
        "move_left_fast" to "move cursor left fast",
        "move_right_slow" to "move cursor right slow",
        "move_right_fast" to "move cursor right fast",
        "move_up_left_slow" to "move cursor up-left slow",
        "move_up_left_fast" to "move cursor up-left fast",
        "move_up_right_slow" to "move cursor up-right slow",
        "move_up_right_fast" to "move cursor up-right fast",
        "move_down_left_slow" to "move cursor down-left slow",
        "move_down_left_fast" to "move cursor down-left fast",
        "move_down_right_slow" to "move cursor down-right slow",
        "move_down_right_fast" to "move cursor down-right fast",
        "stop" to "stop the cursor",
        "click" to "click at the cursor",
        "drag_toggle" to "start or end a drag at the cursor",
        "grid_pick_1" to "grid: pick top-left cell",
        "grid_pick_5" to "grid: pick centre cell",
        "grid_pick_9" to "grid: pick bottom-right cell",
        "back" to "go back",
        "none" to "do nothing (not a deliberate command: noise, speech, or unclear)",
    )

    /** Default global bindings: sound sequence -> action key. */
    val DEFAULT_BINDINGS: Map<List<String>, String> = linkedMapOf(
        listOf("rise") to "swipe_up",
        listOf("fall") to "swipe_down",
        listOf("arch") to "swipe_right",
        listOf("dip") to "swipe_left",
        listOf("click") to "tap",
        listOf("hiss") to "back",
        listOf("flat") to "long_press",
        listOf("click", "click", "click") to "listen_for_phrase",   // 2026-09-28 (user): a pop counts as a click
        listOf("click", "click") to "home",
        listOf("hiss", "click") to "back"
        // 2026-09-28 (user): "pop" and "pop pop" removed (a pop is a click at intake). NOTE: tools/gen_vocab.py would
        // revert this table; it has already differed from finetune/vox/schema.py since 2026-09-27 (pop pop). Do not run it.
    )
    // After the fold "click pop" cannot occur (pop folds to click), so this freed sequence is harmless; kept as is.
    val FREED_SEQUENCES = listOf(listOf("click", "pop"))

    /** App-only bindings: resolved by the rule table in every decider mode, never shown to a model (not in ACTIONS). */
    val APP_ONLY_ACTIONS: Map<String, String> = linkedMapOf(
        "forward" to "go forward",
    )
    val APP_ONLY_BINDINGS: Map<List<String>, String> = linkedMapOf(
        listOf("click", "hiss") to "forward"
    )

    val APPS: Map<String, String> = linkedMapOf(
        "com.zhiliaoapp.musically" to "TikTok",
        "com.google.android.youtube" to "YouTube",
        "com.google.android.apps.maps" to "Google Maps",
        "com.spotify.music" to "Spotify",
        "com.instagram.android" to "Instagram",
        "com.amazon.kindle" to "Kindle",
        "com.google.android.apps.photos" to "Google Photos",
        "com.android.chrome" to "Chrome",
        "com.whatsapp" to "WhatsApp",
        "com.google.android.GoogleCamera" to "Camera",
        "org.videolan.vlc" to "VLC",
        "com.reddit.frontpage" to "Reddit",
        "com.google.android.apps.docs" to "Google Docs",
        "com.duolingo" to "Duolingo",
        "com.netflix.mediaclient" to "Netflix",
        "com.pinterest" to "Pinterest",
    )
    val PHRASES: Map<String, List<String>> = linkedMapOf(
        "back" to listOf("go back", "back", "previous screen"),
        "home" to listOf("go home", "home screen", "home"),
        "open_camera" to listOf("open camera", "camera", "launch the camera"),
        "take_photo" to listOf("take a picture", "snap a photo", "photo"),
        "next_item" to listOf("next", "skip", "next one"),
        "previous_item" to listOf("go back one", "the one before"),
        "play_pause" to listOf("pause", "play", "resume"),
        "volume_up" to listOf("louder", "volume up"),
        "volume_down" to listOf("quieter", "volume down"),
        "scroll_down" to listOf("scroll down", "down a bit"),
        "scroll_up" to listOf("scroll up", "up a bit"),
        "like" to listOf("like this", "heart it"),
        "notifications" to listOf("show notifications", "open notifications"),
        "recents" to listOf("recent apps", "show open apps"),
        "zoom_in" to listOf("zoom in", "closer"),
        "zoom_out" to listOf("zoom out", "further", "shrink")
    )

    val SCREEN_KIND = listOf("video feed", "video player", "scrolling list", "photo viewer", "map", "document", "camera viewfinder", "web page", "text entry", "dialog", "home screen", "other")
    val SCREEN_MEDIA = listOf("playing", "paused", "none")
    val SCREEN_SCROLL = listOf("can scroll both ways", "at the top", "at the bottom", "not scrollable")
    val SCREEN_KEYBOARD = listOf("open", "hidden")

    const val POLICY = "Pick the phone action for the vocal gesture just heard. Only act on deliberate gestures: if it sounds like talking, laughing, coughing or background music, or a hum is noisy, very short, or changes pitch by only a small amount (except a flat hum), choose do nothing. A flat hum must last at least 400 ms to count. A hiss longer than 1 s or that sounds like background noise is not deliberate. The user's rule for the current app overrides their global rules, which override the defaults. Rules for other apps do not apply. A gesture sequence with no binding means do nothing. Cursor mode is switched on and off by the device button. In cursor mode: rise/fall/arch/dip move the cursor up/down/right/left, fast if loud else slow; a pop clicks, a flat hum stops, a hiss goes back, unless a rule says otherwise. In listening mode, map the spoken phrase to the action it asks for, using the user's phrase rules first. The screen line only breaks ties for phrases: 'next'/'previous' mean swiping in a feed, photo viewer or document; 'pause' when already paused or 'play' when already playing means do nothing. Never change an explicit gesture or rule because of the screen."
    // Model input, byte-identical to finetune's generator (state_parity.json): it still says "click pop", as the models were
    // trained. The app owns the listen gesture itself ("pop pop", VoxService.resolveInput) until the data is regenerated.
    const val DEFAULTS_TEXT = "defaults: rise=swipe up, fall=swipe down, arch=swipe right, dip=swipe left, pop=tap, hiss=go back, long flat hum=long-press, click pop=listen for a phrase, click click=go home, hiss click=go back"

    /** Screen tie-breaker for spoken phrases (generate.py). */
    val SCREEN_NEXT: Map<String, String> = linkedMapOf(
        "video feed" to "swipe_up",
        "photo viewer" to "swipe_left",
        "document" to "swipe_left",
    )
    val SCREEN_PREV: Map<String, String> = linkedMapOf(
        "video feed" to "swipe_down",
        "photo viewer" to "swipe_right",
        "document" to "swipe_right",
    )
    val PAUSE_WORDS = setOf("hold on", "pause", "stop the video")
    val PLAY_WORDS = setOf("keep playing", "play", "resume")

    /** Wordings used when the app writes a profile binding as a rule sentence (first training wording each). */
    val GESTURE_WORDS: Map<String, String> = linkedMapOf(
        "rise" to "a rising hum",
        "fall" to "a falling hum",
        "arch" to "an arch hum (up then down)",
        "dip" to "a dip hum (down then up)",
        "flat" to "a long flat hum",
        "pop" to "a pop",
        "click" to "a tongue click",
        "hiss" to "a hiss",
    )
    const val APP_RULE_TEMPLATE = "In {app}, {g} means {a}."
    const val GLOBAL_RULE_TEMPLATE = "Everywhere, {g} means {a}."
    const val DISABLE_RULE_TEMPLATE = "In {app}, ignore {g}."
    const val PHRASE_RULE_TEMPLATE = "When I say '{p}', {a}."

    fun screenText(kind: String, media: String, scroll: String, keyboard: String): String =
        "screen: $kind; media $media; scroll $scroll; keyboard $keyboard"
}
