// GENERATED by firmware/tools/gen_test_sounds.py -- do not edit. Regenerate with tools/build.sh.
// Canned sound lines, produced by running the Python reference extractor (extractor/vox_extract)
// on its SYNTHETIC test clips (extractor/vectors). Used only for link/app tests (serial `send`).
#pragma once
#include <stdint.h>

#define VOX_TEST_SOUNDS_DIGEST "851a102482a68eb9"
#define VOX_VOCAB_DIGEST "139d86bd72e13ae5"
#define VOX_EXTRACTOR_SRC_SHA "fc94951efe059b20"

struct VoxTestSound { const char *name; const char *label; const char *line; uint16_t dur_ms; };
struct VoxTestSeq { const char *name; uint8_t n; uint8_t sound[3]; uint16_t gap_ms[2]; };

static const VoxTestSound VOX_TEST_SOUNDS[] = {
    {"rise", "rise",
     "hum that rises from low to high; pitch change large (over 4 semitones); duration medium (400-1000 ms); tone clear tone; loudness normal; sounds like hum", 490},
    {"fall", "fall",
     "hum that falls from high to low; pitch change large (over 4 semitones); duration medium (400-1000 ms); tone clear tone; loudness normal; sounds like hum", 790},
    {"arch", "arch",
     "hum that rises then falls; pitch change large (over 4 semitones); duration medium (400-1000 ms); tone clear tone; loudness loud; sounds like hum", 920},
    {"dip", "dip",
     "hum that falls then rises; pitch change large (over 4 semitones); duration short (150-400 ms); tone clear tone; loudness normal; sounds like hum", 320},
    {"flat", "flat",
     "hum that stays level; pitch change small (under 2 semitones); duration long (over 1 s); tone clear tone; loudness normal; sounds like hum", 1240},
    {"pop", "pop",
     "a short lip pop; instant sound; loudness normal; sounds like mouth sound", 30},
    {"click", "click",
     "a tongue click; instant sound; loudness normal; sounds like mouth sound", 10},
    {"hiss", "hiss",
     "a hiss; duration short (150-400 ms); loudness loud; sounds like mouth sound", 270},
    {"clickpop.1", "click",
     "a tongue click; instant sound; loudness normal; sounds like mouth sound", 20},
    {"clickpop.2", "pop",
     "a short lip pop; instant sound; loudness normal; sounds like mouth sound", 40},
};
static const int VOX_N_TEST_SOUNDS = 10;

static const VoxTestSeq VOX_TEST_SEQS[] = {
    {"clickpop", 2, {8, 9, 0}, {260, 0}},  // one clip, gaps as extracted from click_pop_30db
    {"poppop", 2, {5, 5, 0}, {250, 0}},  // composed from single sounds, gap 250 ms
    {"riserise", 2, {0, 0, 0}, {900, 0}},  // composed from single sounds, gap 900 ms
};
static const int VOX_N_TEST_SEQS = 3;
